[package]
name = "web-calc"
authors = ["wjl <wlonestar@163.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
wasm-bindgen = "0.2"

[build-dependencies]
lalrpop = "0.20.2"
